### ISSUE TITLE
update for php 8 

### ISSUE THREAD

**Issue by devmrh** [supliu/laravel-query-monitor#18]
please add support for php 8 version

**Comment by kbiits** [comment]
add option --ignore-platform-reqs to composer require command

Note : you will need to add that option in every composer command because the package break your php dependency version

**Comment by alberto-bottarini** [comment]
https://github.com/supliu/laravel-query-monitor/pull/19 :(

**Comment by jansenfelipe** [comment]
Merged! @devmrh @alberto-bottarini 🙌
