### ISSUE TITLE
Install to lumen

### ISSUE THREAD

**Issue by 90uncle** [supliu/laravel-query-monitor#4]
After installation in lumen,the illuminate folder is automatically emptied. What's the reason?

**Comment by Curlson** [comment]
I have a similar problem. My lumen project illuminate dir was cleaned after i installed the package!!

**Comment by jansenfelipe** [comment]
Wow 😢 I didn't do any tests on Lumen. 

I have no idea, it could be some incompatibility with the `laravel/framework` dependency that laravel-query-monitor has?
