### ISSUE TITLE
Very promising

### ISSUE THREAD

**Issue by robov** [supliu/laravel-query-monitor#5]
I found your package and it would be an asome usecase to check what is going on with my spa calling my backend. 
When my vue-SPA logs in through graphql, the login works fine
When I enable your logger I get this error, and this breaks to login flow

`# Query recived:
# SQL: select * from `users` where `email` = 'user@test.com' limit 1
# Time: 0.00051 seconds

   ErrorException 

  Array to string conversion

  at vendor/laravel/framework/src/Illuminate/Support/Str.php:449
    445| 
    446|         $result = array_shift($segments);
    447| 
    448|         foreach ($segments as $segment) {
  > 449|             $result .= (array_shift($replace) ?? $search).$segment;
    450|         }
    451| 
    452|         return $result;
    453|     }
`

**Comment by jansenfelipe** [comment]
@robov it seems that $ bindings is not arriving correctly for you. Try using version 1.0.1 that I just fixed.

**Comment by jansenfelipe** [comment]
Run the artisan command with new option `--debug` to actually see what's coming to the monitor ;-)
