### ISSUE TITLE
No issue but request to add a line in readme file

### ISSUE THREAD

**Issue by ziauddin** [supliu/laravel-query-monitor#7]
First of all I dont know how to communicate with developer in github. So I create an issue to request to you to add 3rd step in the readme file.
3. add Supliu\LaravelQueryMonitor\ServiceProvider::class in config/app.php in provider section

And also Thanks for such a nice tools.

**Comment by swichers** [comment]
Why did you need to add that? Seems to work for me following the instructions as-is (composer require, run the publish command). What problem(s) were you having that were fixed by adding a reference to the service provider?

**Comment by ziauddin** [comment]
Yes. You are right. May be I was forgot to restart my server.
